### PR TITLE
ci(winget): match architecture-specific installers

### PR DESCRIPTION
**Pull request by sitiom**
Created a PR for 1.0.5 on winget-pkgs to reflect this change (should also fix the workflow errors):
- https://github.com/microsoft/winget-pkgs/pull/195077

### CODE REVIEW

**Comment by smartfrigde** [comment]
Thanks!

**Comment by sitiom** [comment]
@smartfrigde https://github.com/Legcord/winget-pkgs no longer exists? https://github.com/Legcord/Legcord/actions/runs/12550490386/job/34993335667

**Comment by sitiom** [comment]
> @smartfrigde [Legcord/winget-pkgs](https://github.com/Legcord/winget-pkgs?rgh-link-date=2024-12-31T03%3A40%3A57Z) no longer exists? [Legcord/Legcord/actions/runs/12550490386/job/34993335667](https://github.com/Legcord/Legcord/actions/runs/12550490386/job/34993335667)

Bump

**Comment by sitiom** [comment]
> @smartfrigde [Legcord/winget-pkgs](https://github.com/Legcord/winget-pkgs?rgh-link-date=2024-12-31T03%3A40%3A57Z) no longer exists? [Legcord/Legcord/actions/runs/12550490386/job/34993335667](https://github.com/Legcord/Legcord/actions/runs/12550490386/job/34993335667)

https://github.com/Legcord/Legcord/actions/runs/12890546783/job/35940378620
image
Please update the access token and make sure it has access to the winget-pkgs repo

**Comment by sitiom** [comment]
> [Legcord/Legcord/actions/runs/12890546783/job/35940378620](https://github.com/Legcord/Legcord/actions/runs/12890546783/job/35940378620) image
> Please update the access token and make sure it has access to the winget-pkgs repo

@smartfrigde bump

**Comment by smartfrigde** [comment]
@sitiom 
https://github.com/Legcord/Legcord/actions/runs/13311356942/job/37175502411

Looks like it works now, thanks for a reminder

**Comment by sitiom** [comment]
I actually opened up a PR by myself, we'll gonna know if it works on the next release 😅.

**Comment by sitiom** [comment]
@smartfrigde Action is failing again https://github.com/Legcord/Legcord/actions/runs/13882127918/job/38842025970

**Comment by smartfrigde** [comment]
Weird, I didn't do anything with the PAT

**Comment by smartfrigde** [comment]
@sitiom Does this look okay?
obraz

**Comment by sitiom** [comment]
No, you should use a **classic PAT** with the `public_repo` scope:

example

**Comment by sitiom** [comment]
Now it works 🎉 https://github.com/microsoft/winget-pkgs/pull/239171

**Comment by smartfrigde** [comment]
Thank you!

**Comment by sitiom** [comment]
@smartfrigde another error https://github.com/Legcord/Legcord/actions/runs/15259364037/job/42914096021:

image

I also noticed https://github.com/Legcord/winget-pkgs has been outdated for a while now. Please install [Pull](https://github.com/apps/pull) on the repo to ensure that it is constantly updated.

**Comment by sitiom** [comment]
> @smartfrigde another error https://github.com/Legcord/Legcord/actions/runs/14821514521/job/41609102078:
> 
> image
> 
> I also noticed https://github.com/Legcord/winget-pkgs has been outdated for a while now. Please install [Pull](https://github.com/apps/pull) on the repo to ensure that it is constantly updated.

Bump

**Comment by sitiom** [comment]
@smartfrigde bump

**Pull request merged**
