### PR TITLE
add(clientmod): equicord

### PR DESCRIPTION
**Pull request by refurbishing**
* adds [Equicord](https://github.com/Equicord/Equicord) a fork of [Vencord](https://github.com/Vendicated/Vencord), with over 300+ plugins, and with 148 stargazers.

### CODE REVIEW

**Comment by SomeAspy** [comment]
I assume this cannot be run side-by-side with vencord?

**Comment by refurbishing** [comment]
> I assume this cannot be run side-by-side with vencord?

you're correct maybe i'll look to find a way to make it that you can enable only one.

**Comment by refurbishing** [comment]
that was easier then what i thought.

**Comment by refurbishing** [comment]
Okay, I'm pretty sure there aren't anymore issues and this can get merged.

**Comment by smartfrigde** [comment]
LGTM

**Pull request merged**
